MODEL:
    MODEL_NAME: "inception_v1_flowers"
    PRETRAIN_MODEL: "inception_v1"
    PRETAIN_MODEL_URL : "http://download.tensorflow.org/models/inception_v1_2016_08_28.tar.gz"
    PRETAIN_MODEL_PATH : "/data/pretain_model/inception_v1/inception_v1.ckpt"
    EXCLUDE_NODES:
     - "InceptionV1/Logits"
     - "InceptionV1/AuxLogits"
    INPUT_HEIGHT: 224
    INPUT_WIDTH: 224
    CLASSES: 5

TRAIN:
    BATCH_SIZE : 64
    EPOCHS_COUNT : 20
    LEARNING_RATE : 0.00001
    KEEP_PROB : 0.5
    TRAIN_EPOCHS_BEFORE_DECAY: 5
    TRAIN_RATE_DECAY_FACTOR: 0.7
    TF_RECORDS_PATH : "/data/flowers"

EVAL:
    BATCH_SIZE : 200
    TF_RECORDS : "/data/flowers"


TEST:
    BATCH_SIZE : 200
    TF_RECORDS : ""
    OUTPUT_PATH : "/data/outputs/inception_resnet_v2_flowers"