MODEL:
    MODEL_NAME: "inception_resnet_v2_flowers"
    PRETRAIN_MODEL: "inception_resnet_v2"
    PRETAIN_MODEL_URL: "http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz"
    PRETAIN_MODEL_PATH: "/data/pretain_model/inception_resnet_v2/inception_resnet_v2_2016_08_30.ckpt"
    EXCLUDE_NODES:
      - 'InceptionResnetV2/Logits'
      - 'InceptionResnetV2/AuxLogits'
    INPUT_HEIGHT: 299
    INPUT_WIDTH: 299
    CLASSES: 5

TRAIN:
    BATCH_SIZE : 32
    EPOCHS_COUNT : 10
    LEARNING_RATE : 0.0001
    KEEP_PROB : 0.5
    TRAIN_EPOCHS_BEFORE_DECAY: 2
    TRAIN_RATE_DECAY_FACTOR: 0.9
    TF_RECORDS_PATH : "/data/flowers"

EVAL:
    BATCH_SIZE : 200
    TF_RECORDS : "/data/flowers"


TEST:
    BATCH_SIZE : 200
    TF_RECORDS : ""
    OUTPUT_PATH : "/data/outputs/inception_resnet_v2_flowers"