MODEL:
    MODEL_NAME: "vgg_16_ft_flowers"
    PRETRAIN_MODEL: "vgg_16"
    PRETAIN_MODEL_URL: "http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz"
    PRETAIN_MODEL_PATH: "/data/pretain_model/vgg_16/vgg_16_2016_08_28.ckpt"
    INPUT_HEIGHT: 224
    INPUT_WIDTH: 224
    CLASSES: 5

TRAIN:
    BATCH_SIZE : 64
    EPOCHS_COUNT : 5
    LEARNING_RATE : 0.0001
    KEEP_PROB : 0.5
    TRAIN_EPOCHS_BEFORE_DECAY: 2
    TRAIN_RATE_DECAY_FACTOR: 0.7
    TF_RECORDS_PATH : "/data/flowers"

EVAL:
    BATCH_SIZE : 100
    TF_RECORDS : "/data/flowers"


TEST:
    BATCH_SIZE : 200
    TF_RECORDS : ""
    OUTPUT_PATH : "/data/outputs/tiny_imagenet"